# cloudbuild.yaml

steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/snake-game', '.']

images:
- 'gcr.io/$PROJECT_ID/snake-game'

- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'snake-game'
  - '--image=gcr.io/$PROJECT_ID/snake-game'
  - '--platform=managed'
  - '--region=us-central1'
  - '--port=8080'
